# Generated by Django 6.0.2 on 2026-03-30 11:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseTopic',
            fields=[
                ('topic_id', models.AutoField(primary_key=True, serialize=False)),
                ('module_name', models.CharField(max_length=100)),
                ('topic_name', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='myapp.course')),
            ],
            options={
                'ordering': ('course', 'module_name', 'topic_name'),
                'unique_together': {('course', 'module_name', 'topic_name')},
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_name', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit mobile number starting with 6-9.', regex='^[6-9]\\d{9}$')])),
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_email', models.EmailField(max_length=254, unique=True)),
                ('courses', models.ManyToManyField(related_name='staffs', to='myapp.course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('interview_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('experience', models.CharField(blank=True, max_length=100, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], default='ongoing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='myapp.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_name', models.CharField(help_text='Example: Morning Batch', max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='myapp.staff')),
            ],
            options={
                'ordering': ['start_time'],
                'unique_together': {('staff', 'batch_name')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('source', models.CharField(default='biometric', max_length=20)),
                ('device_sn', models.CharField(blank=True, max_length=50, null=True)),
                ('verify_code', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='myapp.staff')),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='StaffLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_date', models.DateField(help_text='Date this staff member started')),
                ('leave_balance', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('leave_used', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('last_credited', models.DateField(blank=True, help_text='Last month-start on which 1 day was credited', null=True)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leave', to='myapp.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=100)),
                ('join_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('student_email', models.EmailField(max_length=254, unique=True)),
                ('student_contact', models.CharField(blank=True, max_length=20)),
                ('mode', models.BooleanField(choices=[(True, 'Offline'), (False, 'Online')], default=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='myapp.batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='myapp.course')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='myapp.staff')),
            ],
        ),
        migrations.CreateModel(
            name='StaffCourseProgress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to='myapp.staff')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_progress', to='myapp.coursetopic')),
            ],
            options={
                'unique_together': {('staff', 'topic')},
            },
        ),
        migrations.CreateModel(
            name='StaffLeaveUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('leave_type', models.CharField(choices=[('paid', 'Paid Leave'), ('absent', 'Absent (Unpaid)')], default='absent', max_length=10)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves_taken', to='myapp.staff')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('staff', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, choices=[(True, 'Present'), (False, 'Absent')], null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='myapp.student')),
            ],
            options={
                'unique_together': {('student', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StudentTopicProgress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('marks', models.IntegerField(blank=True, null=True)),
                ('sign', models.CharField(help_text='Staff full name', max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='myapp.student')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='myapp.coursetopic')),
            ],
            options={
                'unique_together': {('student', 'topic')},
            },
        ),
    ]
