# Generated by Django 6.0.2 on 2026-02-18 04:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursetopic',
            options={'ordering': ('course', 'module_name', 'topic_name')},
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='contact',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit mobile number starting with 6-9.', regex='^[6-9]\\d{9}$')]),
        ),
    ]
