# Generated by Django 6.0.2 on 2026-03-20 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_coursetopic_options_alter_course_course_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffCourseProgress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to='myapp.staff')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_progress', to='myapp.coursetopic')),
            ],
            options={
                'unique_together': {('staff', 'topic')},
            },
        ),
    ]
