# Generated by Django 6.0.2 on 2026-03-20 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_staffcourseprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_date', models.DateField(help_text='Date this staff member started')),
                ('leave_balance', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('leave_used', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('last_credited', models.DateField(blank=True, help_text='Last month-start on which 1 day was credited', null=True)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leave', to='myapp.staff')),
            ],
        ),
        migrations.CreateModel(
            name='StaffLeaveUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('leave_type', models.CharField(choices=[('paid', 'Paid Leave'), ('absent', 'Absent (Unpaid)')], default='absent', max_length=10)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves_taken', to='myapp.staff')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('staff', 'date')},
            },
        ),
    ]
