# Generated by Django 6.0.2 on 2026-04-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_companyinterview_location_companyinterview_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.CharField(max_length=500),
        ),
    ]
