# Generated by Django 6.0.2 on 2026-03-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_staffleave_staffleaveusage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
        name='attendance',
        unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='device_sn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='source',
            field=models.CharField(choices=[('biometric', 'Biometric'), ('manual', 'Manual Entry'), ('admin', 'Admin Entry')], default='biometric', max_length=20),
        ),
        migrations.AddField(
            model_name='attendance',
            name='verify_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='wifi_verified',
        ),
    ]
