# Generated by Django 6.0.2 on 2026-03-26 08:08
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['date', 'time']},
        ),
        migrations.AddField(
            model_name='attendance',
            name='punch_type',
            field=models.CharField(choices=[('in', 'Check In'), ('out', 'Check Out')],max_length=3),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='source',
            field=models.CharField(default='biometric', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.staff'),
        ),
    ]
"""from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['date', 'time']},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='punch_type',
            field=models.CharField(choices=[('in', 'Check In'), ('out', 'Check Out')], default='in', max_length=3),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='source',
            field=models.CharField(default='biometric', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.staff'),
        ),
    ]
"""
"""
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['date', 'time']},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='punch_type',
            field=models.CharField(choices=[('in', 'Check In'), ('out', 'Check Out')], default='in', max_length=3),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 3, 26, 8, 8, 38, 788179, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='source',
            field=models.CharField(default='biometric', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.staff'),
        ),
    ]
"""
