# Generated by Django 6.0.2 on 2026-03-26 08:11

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 3, 26, 8, 11, 4, 103673, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='myapp.staff'),
        ),
    ]
