# Generated by Django 6.0.2 on 2026-03-27 04:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_attendance_date_alter_attendance_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 3, 27, 4, 36, 29, 323096, tzinfo=datetime.timezone.utc)),
        ),
    ]
