# Generated by Django 6.0.2 on 2026-03-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='punch_type',
            field=models.CharField(choices=[('in', 'Check In'), ('out', 'Check Out')], max_length=3, null=True),
        ),
    ]
