# Generated by Django 6.0.2 on 2026-03-27 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_attendance_punch_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='punch_type',
        ),
    ]
