# Generated by Django 6.0.2 on 2026-03-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_attendance_punch_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='punch_type',
            field=models.CharField(choices=[('in', 'Check In'), ('out', 'Check Out')], default='in', max_length=3),
            preserve_default=False,
        ),
    ]
