# Generated by Django 6.0.2 on 2026-03-31 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_jobapplication_resume'),
        ('myapp', '0004_companyinterview_location_companyinterview_salary_and_more'),
    ]

    operations = [
    ]
