# Generated by Django 6.0.2 on 2026-03-31 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_companyinterview'),
        ('myapp', '0013_remove_attendance_punch_type'),
    ]

    operations = [
    ]
