# Generated by Django 6.0.2 on 2026-03-31 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_merge_20260331_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProgressDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_topics', models.IntegerField(default=0)),
                ('finished_topics', models.IntegerField(default=0)),
                ('ready_to_placement', models.BooleanField(default=False)),
                ('placed', models.BooleanField(default=False)),
                ('no_of_interviews', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to='myapp.student')),
            ],
        ),
    ]
