# Generated by Django 6.0.2 on 2026-04-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_studentprogressdashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='course',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='student',
            field=models.CharField(max_length=100),
        ),
    ]
