# Generated by Django 6.0.2 on 2026-04-10 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_jobapplication_course_jobapplication_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinterview',
            name='interview_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
