# Generated by Django 6.0.2 on 2026-04-10 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_companyinterview_interview_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
