# Generated by Django 6.0.2 on 2026-04-13 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_jobapplication_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('total_days', models.IntegerField()),
                ('present_days', models.IntegerField()),
                ('absent_days', models.IntegerField()),
                ('salary', models.FloatField()),
                ('deduction', models.FloatField()),
                ('net_salary', models.FloatField()),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_on', models.DateTimeField(blank=True, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.staff')),
            ],
            options={
                'unique_together': {('staff', 'month')},
            },
        ),
    ]
