# Generated by Django 6.0.2 on 2026-04-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_payroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
